### PR TITLE
resolve wrong declaration and one warning

### PR DESCRIPTION
**Pull request by S-VIN**
1) Add default to switch to resolve warning.
2) Fix wrong declaration.

### CODE REVIEW

**Comment by yurybotov** [comment]
Will do it ASAP. And add any more corrections for setCursor.

**Review by yurybotov — APPROVED** [review]
I add some small changes

**Comment by S-VIN** [comment]
@yurybotov  please, merge this PR by yourself, if you are ended to change  setCursor().

**Comment by yurybotov** [comment]
Wait for review. I could not change setCursor anymore.

**Comment by S-VIN** [comment]
pls, check this PR. I'll create another one with issue fixing. @nkrkv @igor605ds

**Review by nkrkv — APPROVED** [review]

**Review by nomad605dis — APPROVED** [review]
LGTM

**Pull request merged**
